### PR TITLE
Update bootstrap 4.6.0 to 5.3.0

### PR DESCRIPTION
**Pull request by dmsimard**

### CODE REVIEW

**Comment by dmsimard** [comment]
This is just updating the CSS files and looking at the result. There are a few broken bits here and there like the color of the status, the theme switcher, etc.

I've recorded a short gif:
Peek 2021-11-20 16-11

**Comment by dmsimard** [comment]
Moving this out of 1.5.8, it should be bundled with the update of django: https://github.com/ansible-community/ara/pull/360

**Comment by dmsimard** [comment]
This is a bit of a pain. I thought it would be fine to land in 1.6.0 but it requires more work than expected so I am leaving it out of scope for now, we can do it in a later dot release to avoid delaying 1.6.0 further.

**Comment by dmsimard** [comment]
Searched a bit and there's some upgrade resources here:
- https://getbootstrap.com/docs/5.0/migration/
- https://www.web3canvas.com/convert-bootstrap-4-to-5-migration-guide/

**Comment by dmsimard** [comment]
Bootstrap is up to 5.3 now: https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/

I may take this opportunity to revisit and clean up the templates but this is on my radar.

**Comment by dmsimard** [comment]
Some notes about upgrading bootstrap from 4 to 5:

- There's a built-in dark theme now: https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/#dark-mode
- jQuery is no longer necessary: https://getbootstrap.com/docs/5.3/getting-started/javascript/#optionally-using-jquery

**Comment by dmsimard** [comment]
At first glance there is a lot of work to do. I expected to need to refresh every page and template.

I have made progress with the navbar and theme switcher:
Peek 2023-06-26 00-05

The good news is that we only need the base bootstrap css now, there is no longer a need for the individual bootswatch templates.

The search accordions no longer work. I will look at that next.

**Comment by dmsimard** [comment]
I spent some time on the accordion for the playbook search. Lots of cleanup and I put it into it's own partial.
It took a while but it should be simple enough to re-use the same pattern for the hosts and tasks search accordions.

Here's a quick video showing the comparison between the current implementation and the work in progress:

https://github.com/ansible-community/ara/assets/1291204/e561cdf3-524d-481d-add9-5d01e0abbe1b

**Comment by dmsimard** [comment]
Spent (probably too much) time theming the accordion, what it looks like in light and dark:

https://github.com/ansible-community/ara/assets/1291204/e018545e-0ca8-459f-8b1d-1c4854e758db

https://github.com/ansible-community/ara/assets/1291204/9e786cfc-4345-4393-b918-5b63783fe5ff

**Comment by dmsimard** [comment]
Here's a first commit that demonstrates a first chunk of the progress.

I have done some more improvements on the playbooks page and I still need to fix the CLI options modal.

It looks like this:
Peek 2023-07-01 22-01

Peek 2023-07-01 22-02

**Comment by dmsimard** [comment]
I've fixed the about modal as well as the CLI configuration modal and I gave it a bit of love so they're slightly less barebones. We can improve it further later, it is mostly out of scope for now.

More comparison gifs!

## About
Peek 2023-07-02 02-49

## CLI (light)
Peek 2023-07-02 02-59


## CLI (dark)
Peek 2023-07-02 02-58

**Comment by dmsimard** [comment]
A drive-by improvement to the report and CLI buttons, they are larger and easier to click:

Peek 2023-07-02 15-59

Peek 2023-07-02 16-00

**Comment by dmsimard** [comment]
I've fixed and cleaned up the hosts page:

Peek 2023-07-02 17-48

Peek 2023-07-02 17-47

**Comment by dmsimard** [comment]
I've fixed and cleaned up the Tasks page:

Peek 2023-07-02 20-18

Peek 2023-07-02 20-21

**Comment by dmsimard** [comment]
I've fixed and cleaned up the playbook report page, some comparison gifs:

Peek 2023-07-03 22-19

Peek 2023-07-03 22-18

Aside from the other little things to fix (in the commit TODOs), there remains more or less 4 pages to refresh:
- host facts / results
- task result detail
- file view
- record view

**Comment by hille721** [comment]
the GIFs looking really promising. Thanks for this hard work!
Let me know when you are done from your side then I can check it in more detail and can give a review.

**Comment by dmsimard** [comment]
> the GIFs looking really promising. Thanks for this hard work!
> Let me know when you are done from your side then I can check it in more detail and can give a review.

Much appreciated, thank you @hille721 !

I am expecting to be able to make some more progress this week.
With a bit of luck, I could have something that is ready for a first real review sometime next week.

In any case, once I feel it is ready, I will put it up on something like dev.demo.recordsansible.org so it is easy to compare side-by-side with the live demo running the same data.

**Comment by dmsimard** [comment]
I've fixed and updated the task result detail page:

Peek 2023-07-08 14-33

Peek 2023-07-08 14-32

I also fixed the pygments css theming for viewing files but I haven't yet figured out the right way to re-write the line highlighting that was done with jquery (that we no longer have): https://github.com/ansible-community/ara/blob/578ef8149ac24ad37944f5bac9e5d478fced36c3/ara/ui/templates/file.html#L22-L34

**Comment by dmsimard** [comment]
I think I've got something working for the file line highlighting. I dislike javascript and better ideas are welcomed but this appears to do the job without jquery:
```html
<!-- Line highlighting -->
<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    if (window.location.hash.length) {
      // Recover the line number in the URL anchor and highlight it
      var anchor = window.location.hash;
      var span = document.querySelector(anchor);
      span.classList.add("hll");
    }

    document.addEventListener("click", function(e) {
      // When a link is clicked
      if(e.target.tagName == "A") {
        // Remove the previously highlighted line if there is one
        if (window.location.hash.length) {
          var anchor = window.location.hash;
          var span = document.querySelector(anchor);
          span.classList.remove("hll")
        }

        // Highlight the new one
        var anchor = e.target.getAttribute("href");
        var span = document.querySelector(anchor);
        span.classList.add("hll");
      }
    });
  });
</script>
```

New:
Peek 2023-07-08 19-07

Old:
Peek 2023-07-08 19-09

**Comment by dmsimard** [comment]
By the way, a link to a static build from one of the CI jobs: https://bac7d5eacdcb55f6288a-aaed4513bc0475e9932dd89978f40d93.ssl.cf1.rackcdn.com/340/181a857cbee0a9f6e4bebc45ea4c07dbb733ba75/check/ara-basic-ansible-8/b85379c/server/static/

The UI is a bit different since there is no database backend (i.e, no search) but it gives a good idea of what it looks like at this time.

**Comment by dmsimard** [comment]
The string length stress test is showing some funky results that should be looked at: 
image

Most (all?) text truncation happens in django templating, maybe we could/should consider doing it in css instead: https://getbootstrap.com/docs/5.2/helpers/text-truncation/

**Comment by hille721** [comment]
> By the way, a link to a static build from one of the CI jobs:

I checked that on my phone and it seems to be that there are some problems regarding responsiveness. 

e.g.

**Comment by dmsimard** [comment]
Thanks, I'll check it out.

css-is-awesome-20090407-142244

**Comment by dmsimard** [comment]
@hille721 I believe to have fixed the two responsiveness oddities you've picked up on, thanks !

**Comment by dmsimard** [comment]
There's a mobile responsiveness issue when viewing files:
IMG_20230727_124445

**Comment by dmsimard** [comment]
By the way: I don't know where this is going yet but I am attempting trying to clean up and simplify bits of django templating. It's been pretty experimental and I'm not really happy with how it's looking right now so there is more work to do.

For example, there's new partial templates (meant to be included) under the ``search`` and ``tables`` directories.

It's out of scope of the bootstrap update and the UI refresh but they both touch pretty much every template so it's an opportunity to work through that at the same time.

The templating has grown organically over the years. We didn't necessarily make re-usable/standardized components that could be logically re-grouped and easily included in larger blocks of templating to simplify things where it makes sense.

With the power of experience and hindsight, we can do better :p

**Comment by ianw** [comment]
One thing I noticed is that I run a 1200 x 1920 right-portrait monitor and the content is too wide, but also I don't have a horizontal scroll bar either.

image

**Comment by dmsimard** [comment]
Hi @ianw, thanks for looking !

> One thing I noticed is that I run a 1200 x 1920 right-portrait monitor and the content is too wide, but also I don't have a horizontal scroll bar either.

I've noticed this behavior in the previous version of bootstrap as well but I haven't researched it.

Just to confirm, can you still scroll horizontally even though there's no horizontal scroll bar ?
I can do it locally by resizing my window small enough that the table no longer fits, clicking anywhere on the table and then using horizontal arrows on my keyboard or my mouse's horizontal scroll wheel.

It looks like this:
Peek 2023-07-27 21-00


I don't know what's the right fix but it's not the best UX for sure.

**Comment by dmsimard** [comment]
@ianw btw I also tried to make sure that the static generation still works properly, here's one from this PR from Zuul: https://b860d1e0b452f4998247-bef371a08164594183d849ff8c4e5a1f.ssl.cf1.rackcdn.com/340/7e2734008a4327dae7b3131c4a45f3a147f91c24/check/ara-basic-ansible-core-2.15/3f70c2e/server/static/index.html

Let me know if anything stands out to you :)

**Comment by ianw** [comment]
> Just to confirm, can you still scroll horizontally even though there's no horizontal scroll bar ? I can do it locally by resizing my window small enough that the table no longer fits, clicking anywhere on the table and then using horizontal arrows on my keyboard or my mouse's horizontal scroll wheel.

Yes, if I click to select the page, I can use left/right to move but the page still doesn't show any sort of horizontal scroll-bar to indicate the length.

**Comment by ianw** [comment]
> @ianw btw I also tried to make sure that the static generation still works properly, here's one from this PR from Zuul: https://b860d1e0b452f4998247-bef371a08164594183d849ff8c4e5a1f.ssl.cf1.rackcdn.com/340/7e2734008a4327dae7b3131c4a45f3a147f91c24/check/ara-basic-ansible-core-2.15/3f70c2e/server/static/index.html
> 
> Let me know if anything stands out to you :)

Thanks for considering this

I would say there seems to be a lot of whitespace, and the columns perhaps showing too much of what I don't want to know, causing hiding of what I do.  Perhaps the labels could be folded into a row, and the task name could be on a row so you can see the whole thing too.  I definitely like the full dates (rather than "X hours ago") because often you need to line up timestamps with system logs, etc -- but the format for that and the duration may be a bit verbose and could drop zeros maybe?

**Comment by dmsimard** [comment]
> Yes, if I click to select the page, I can use left/right to move but the page still doesn't show any sort of horizontal scroll-bar to indicate the length.

@ianw I've created an issue to capture this: https://github.com/ansible-community/ara/issues/498

I'm leaving it out of scope of this particular PR, especially since the previous version of bootstrap has the same behavior.
It would be great to improve it sometime.

**Comment by dmsimard** [comment]
> I would say there seems to be a lot of whitespace, and the columns perhaps showing too much of what I don't want to know, causing hiding of what I do. Perhaps the labels could be folded into a row, and the task name could be on a row so you can see the whole thing too. I definitely like the full dates (rather than "X hours ago") because often you need to line up timestamps with system logs, etc -- but the format for that and the duration may be a bit verbose and could drop zeros maybe?

I agree that labels are problematic when there's a couple of them or they are too long. I've known about this but don't believe it was recorded in an issue so I've gone ahead and created one for it: https://github.com/ansible-community/ara/issues/499

For dates it's tricky. The verbose format relieves the confusion from american date formatting versus the rest of the world and I think that's a good thing -- in other words, is this december 7th or july 12th: 12/7/2023 ? Perhaps the timezone could be put in a tooltip which would free up 6 characters worth of width.

For durations we could do something as well. I'll see if I can think of something.

Thanks for the feedback @ianw :)

**Comment by dmsimard** [comment]
My last commit to the PR fixes the tags tooltip and includes a minor fix for the ara_record page.

With this, I think I am done with more or less a first full pass throughout the entire UI.
Need to review some more and then work out how to clean up the django templating like I [intended to do](https://github.com/ansible-community/ara/pull/340#issuecomment-1654210938).

**Comment by dmsimard** [comment]
I fixed the file responsiveness issue I commented on 2 days ago: https://github.com/ansible-community/ara/pull/340#issuecomment-1653985552

To be clear, this isn't a bootstrap regression. It was also an issue before but hey, it's fixed now:

https://github.com/ansible-community/ara/assets/1291204/b9844c7d-7600-4abb-ac8b-a6d90d6c1baa

**Comment by dmsimard** [comment]
For posterity I've recorded a small video of the mobile UI:

https://github.com/ansible-community/ara/assets/1291204/54f2ac65-0263-44ec-acd6-3309560b91d0

**Comment by dmsimard** [comment]
I ran djlint which is a linter for django template things, maybe we can add it to the linter CI job but in the meantime:
```
> djlint ara/ui/templates/ --profile=django

Linting 40/40 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00    


ara/ui/templates/base.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H031 4:0 Consider adding meta keywords. <html lang="en" data
T003 10:30 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
H006 33:6 Img tag should have height and width attributes. <img src="{% static_
T003 94:4 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/distributed_index.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H014 2:9 Found extra blank lines. trip_db %}
T003 5:45 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
H021 22:16 Inline styles should be avoided. <tr style=
T003 41:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/file.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 5:73 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
H025 11:2 Tag seems to be an orphan. <div>
T003 51:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/host.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 4:152 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
T003 23:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/host_index.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 2:113 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
T003 23:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/index.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 2:117 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
T003 23:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/partials/pagination.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H023 14:114 Do not use entity references. &laquo;
H023 18:96 Do not use entity references. &laquo;
H025 24:4 Tag seems to be an orphan. <li class="page-item
H023 27:108 Do not use entity references. &raquo;
H023 31:94 Do not use entity references. &raquo;

ara/ui/templates/partials/playbook_card.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 12:14 Inline styles should be avoided. <h3 style=
H021 21:2 Inline styles should be avoided. <div class="card-bod
H021 72:18 Inline styles should be avoided. <div class="modal-bo
T001 77:28 Variables should be wrapped in a whitespace. {{ playbook.started 
H021 115:8 Inline styles should be avoided. <span class="btn btn

ara/ui/templates/partials/playbook_files.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 15:4 Inline styles should be avoided. <div id="collapse_fi

ara/ui/templates/partials/playbook_hosts.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 15:4 Inline styles should be avoided. <div id="collapse_ho

ara/ui/templates/partials/playbook_records.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 15:4 Inline styles should be avoided. <div id="collapse_re

ara/ui/templates/partials/playbook_results.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 27:16 Inline styles should be avoided. <tr style=
T002 97:250 Double quotes should be used in tags. {% include 'partials
H025 119:4 Tag seems to be an orphan. </form>

ara/ui/templates/partials/result_status_icon.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H025 2:2 Tag seems to be an orphan. <a role="button" cla
H025 4:2 Tag seems to be an orphan. <a role="button" cla
H025 6:2 Tag seems to be an orphan. <a role="button" cla
H025 8:2 Tag seems to be an orphan. <a role="button" cla
H025 10:2 Tag seems to be an orphan. <a role="button" cla

ara/ui/templates/partials/search/hosts.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T002 81:18 Double quotes should be used in tags. {% include "partials
T002 87:18 Double quotes should be used in tags. {% include "partials
T002 93:18 Double quotes should be used in tags. {% include "partials
T002 99:18 Double quotes should be used in tags. {% include "partials
T002 105:18 Double quotes should be used in tags. {% include "partials

ara/ui/templates/partials/tables/host_facts.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 15:4 Inline styles should be avoided. <div id="collapse_ho
H021 22:14 Inline styles should be avoided. <th style=
H021 23:14 Inline styles should be avoided. <th style=
H021 33:16 Inline styles should be avoided. <td data-label="Valu

ara/ui/templates/partials/tables/host_results.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 21:14 Inline styles should be avoided. <td class="bg-transp
H021 62:16 Inline styles should be avoided. <tr style=
T002 129:250 Double quotes should be used in tags. {% include 'partials

ara/ui/templates/partials/tables/hosts.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 9:6 Inline styles should be avoided. <tr style=

ara/ui/templates/partials/tables/playbooks.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 9:6 Inline styles should be avoided. <tr style=
H021 60:16 Inline styles should be avoided. <div class="modal-bo
T001 65:26 Variables should be wrapped in a whitespace. {{ playbook.started 

ara/ui/templates/partials/tables/tasks.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
H021 9:6 Inline styles should be avoided. <tr style=
T002 88:233 Double quotes should be used in tags. {% include 'partials

ara/ui/templates/playbook.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 5:230 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
T003 33:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/record.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 4:88 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
H025 10:2 Tag seems to be an orphan. <div>
T003 19:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/result.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 7:145 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
H021 94:10 Inline styles should be avoided. <table class="table 
H021 97:14 Inline styles should be avoided. <th style=
H021 98:14 Inline styles should be avoided. <th style=
T003 125:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

ara/ui/templates/task_index.html
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T003 2:113 Endblock should have name. Ex: {% endblock body %}. {% endblock %}
T003 28:0 Endblock should have name. Ex: {% endblock body %}. {% endblock %}

Linted 40 files, found 68 errors.

```

**Comment by dmsimard** [comment]
I've finished a last round of review, cleanup and fixing. I think this is good to go but I need to fix the commit history a bit.

Forposterity, all the work split into milestones were pushed to another branch: https://github.com/dmsimard/ara/tree/update-static-assets-archive

**Comment by dmsimard** [comment]
This is good enough and we can iterate on this if there are issues.

This PR has been in progress since Nov 20, 2021 and it's finally merging !

**Pull request merged**
