### PR TITLE
1.6.0rc1 fixes

### PR DESCRIPTION
**Pull request by dmsimard**
I'll keep this PR opened for a while, we can put the fixes we find for rc1 here.

- ui: center the user cell in the playbook list table

### CODE REVIEW

**Comment by hille721** [comment]
The user cell left alignment was intentionally, not accidentally :) 

see: https://github.com/ansible-community/ara/pull/432

**Comment by dmsimard** [comment]
> The user cell left alignment was intentionally, not accidentally :)
> 
> see comment [#431 (comment)](https://github.com/ansible-community/ara/issues/431#issuecomment-1251008718) and pr #432

Oh, I forgot. Let's keep it like that for now then.

UX is hard.

**Comment by dmsimard** [comment]
@hille721 I'm re-opening this but will change the fix -- the table header should be aligned with the cells but right now it's centered:

Selection_060

**Comment by dmsimard** [comment]
I've reverted the change in which we moved host facts below the task results to keep what we had before for now.

There are other ways to improve navigation and UX, one of which I've created an issue about: https://github.com/ansible-community/ara/issues/463

**Comment by dmsimard** [comment]
Thanks for the :+1: @hille721, let's ship it

**Pull request merged**
