### PR TITLE
Add CSRF_TRUSTED_ORIGINS to settings

### PR DESCRIPTION
**Pull request by cosemansbert**
When using a reverse proxy, i was running into errors like the one below when logging into the admin panel.
`WARNING django.security.csrf: Forbidden (Referer checking failed - https://<reverse-proxy-hostname>/admin/login/?next=/admin/ does not match any trusted origins.): /admin/login/`
This modification allowed me to add the reverse proxy hostname to CSRF_TRUSTED_ORIGINS, fixing the login issues.

### CODE REVIEW

**Comment by dmsimard** [comment]
Hi @cosemansbert and thanks for the PR, I haven't bumped into that but I also don't use the admin panel.

I've validated that it's a thing according to the [django docs](https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-trusted-origins).

Could you consider adding it to this dictionary so it gets rendered in the default settings.yaml ?
https://github.com/ansible-community/ara/blob/f366c9f9f2a06311dd67449f1124dca0674563c2/ara/server/settings.py#L268-L294

A small bit of docs [here](https://github.com/ansible-community/ara/blob/master/doc/source/api-configuration.rst) would be appreciated but I can do that too.

**Comment by cosemansbert** [comment]
Hi @dmsimard,
Thanks for the feedback.
I tried implementing the suggestions you made.
Let me know if you see any other issues.

**Comment by dmsimard** [comment]
Hey @cosemansbert, sorry about the delay and please ignore the unrelated CI failures, I'll address them elsewhere.

Did you mean to include a feature for client certificates or would that be in another PR ?

**Comment by cosemansbert** [comment]
Hi @dmsimard, the client certificate feature needs some more cleaning up. I'll submit that later in another PR.

**Comment by dmsimard** [comment]
recheck

**Comment by dmsimard** [comment]
recheck

**Comment by dmsimard** [comment]
recheck

**Comment by dmsimard** [comment]
Thanks for your contribution @cosemansbert and sorry it took so long to merge. It'll be in the next release, 1.5.8.

**Pull request merged**
