### PR TITLE
Allow ARA to be deployed on a "subpath".

### PR DESCRIPTION
**Pull request by apollo13**
By default ARA listens on `localhost:8000/`. Using BASE_PATH this can be changed to ie `/ara/` to have ARA listen on `localhost:8000/ara`. This is not really useful during development but can be helpful when a reverse proxy is in front of ARA.

@dmsimard I realize this is rather late in the 1.6 cycle but I'd love it to be in there.

### CODE REVIEW

**Comment by dmsimard** [comment]
@apollo13 people have asked about this before (most recently [here](https://github.com/ansible-community/ara/issues/428)) but I didn't have good advice -- it was pretty tricky to do with Flask back in the day. I'm happy that it actually turns out to be simple with django.

I'm very late in releasing 1.6.0 due to various circumstances, we can probably include this change.

I will test and review it soon.

**Comment by apollo13** [comment]
Mhm something is wrong here still, looking into it :)

**Comment by apollo13** [comment]
I think it works okay now, currently testing against our AWX setup :)

**Comment by dmsimard** [comment]
Hi @apollo13 and thanks for the PR.

I've tested this successfully using ``gunicorn --access-logfile - --bind 127.0.0.1:8000 ara.server.wsgi`` but it doesn't seem to work with ``ara-manage runserver``.

Is it expected to ?

Do we need to add something in https://github.com/ansible-community/ara/blob/master/ara/server/__main__.py or elsewhere ?

**Comment by apollo13** [comment]
@dmsimard What exactly did you test? I just set `BASE_PATH` to `/test` and tested it with and without `DISTRIBUTED_SQLITE`. Please note that `/` will 404 and only `/test/` will give you something meaningful. Are you sure that `ara-manage` did run against the correct ara version?

**Comment by dmsimard** [comment]
@apollo13 I checked out your branch, modified settings.yaml to have ``BASE_PATH`` to ``/test``:

Screenshot from 2022-11-20 12-06-53

Whether or not there is a trailing slash doesn't appear to make a difference but I could be missing something obvious.

**Comment by apollo13** [comment]
image
This is what it looks like here; I do have a vastly newer Django -- maybe that makes a diff?

**Comment by dmsimard** [comment]
Ohh, I was unexpectedly running off of an old tox venv which still had Django 2.2.

It works with Django 3.2.

My bad :facepalm:

**Pull request merged**
